version: 2
builds:
  - main: ./cmd/frisbii
    binary: frisbii
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 'amd64'
      - 'arm64'
    # Change to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
    mod_timestamp: '{{.CommitTimestamp}}'
    env:
      - CGO_ENABLED=0
universal_binaries:
  - replace: true
archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: darwin
        formats:
          - zip
release:
  mode: keep-existing
changelog:
  disable: true
